### ISSUE TITLE
Layout is wrong in iOS 9

### ISSUE THREAD

**Issue by leavez** [DavdRoman/Bohr#11]
<img width="368" alt="untitled" src="https://cloud.githubusercontent.com/assets/4454541/9374058/c56cba08-4723-11e5-8d6b-5eaf728753c5.png">

**Comment by davdroman** [comment]
Hi there, Leave! Thanks for reporting this issue.

I know exactly what's causing it. It has to do with a little nasty hack used to enable Autolayout usage on `textLabel` and `detailTextLabel`.

Solving this hack in this current version would bring a lot more issues like this because there are multiple cells in the framework that rely too strongly on it.

Nevertheless, I've been working on version 3 for a while now, which doesn't require this hack at all to work. I'm **completely** certain it's not going to take me more than what's left for iOS 9 to be released officially, so I encourage you to wait for it.

**Comment by davdroman** [comment]
Hi again, @leavez!

Just wanted to let you know v3.0.0 alpha 1 is now available and I'd really like for you to give it a try and check if everything's alright :)

**Comment by davdroman** [comment]
Hey @leavez!

Just wanted to let you know alpha 4 just came out. Most iOS 9 layout issues are fixed by now.
