### ISSUE TITLE
ValueDidChange in BOSetting

### ISSUE THREAD

**Issue by gmoledina** [DavdRoman/Bohr#34]
The `setValueDidChangeBlock` method in BOSetting is not exposed in the header file.
I'm wondering how the Model layer can register to be notified for any changes (so without adding itself as a target in the UI layer) ?

**Comment by davdroman** [comment]
This again comes down to the discussion in #32. As Bohr relies uniquely on `NSUserDefaults`, value observation can be achieved simply by observing `NSUserDefaults` directly through the standard KVO mechanism. Again, I didn't originally include support for observation because of the reliance on `NSUserDefaults`, but this is something we definitely need to work on for the next major, storage-agnostic release.

**Comment by gmoledina** [comment]
Oh perfect, thanks for the answer. :+1:
